"use strict";
/**
 * API
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpValidationProblemDetails = void 0;
class HttpValidationProblemDetails extends null {
    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(HttpValidationProblemDetails.attributeTypeMap);
    }
}
exports.HttpValidationProblemDetails = HttpValidationProblemDetails;
HttpValidationProblemDetails.discriminator = undefined;
HttpValidationProblemDetails.attributeTypeMap = [
    {
        "name": "errors",
        "baseName": "errors",
        "type": "{ [key: string]: Array<string>; }"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "number"
    },
    {
        "name": "detail",
        "baseName": "detail",
        "type": "string"
    },
    {
        "name": "instance",
        "baseName": "instance",
        "type": "string"
    }
];
//# sourceMappingURL=httpValidationProblemDetails.js.map