"use strict";
/**
 * API
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProblemDetails = void 0;
class ProblemDetails extends null {
    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ProblemDetails.attributeTypeMap);
    }
}
exports.ProblemDetails = ProblemDetails;
ProblemDetails.discriminator = undefined;
ProblemDetails.attributeTypeMap = [
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "number"
    },
    {
        "name": "detail",
        "baseName": "detail",
        "type": "string"
    },
    {
        "name": "instance",
        "baseName": "instance",
        "type": "string"
    }
];
//# sourceMappingURL=problemDetails.js.map