"use strict";
/**
 * API
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Token = void 0;
class Token {
    static getAttributeTypeMap() {
        return Token.attributeTypeMap;
    }
}
exports.Token = Token;
Token.discriminator = undefined;
Token.attributeTypeMap = [
    {
        "name": "value",
        "baseName": "value",
        "type": "string"
    },
    {
        "name": "expiration",
        "baseName": "expiration",
        "type": "Date"
    }
];
//# sourceMappingURL=token.js.map