/**
 * API
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WeatherForecastDto {
    /**
    * Unique identifier
    */
    'id': number;
    /**
    * Date of the weather forecast
    */
    'date': Date;
    /**
    * Temperature of weather in celcius
    */
    'temperatureC'?: number;
    /**
    * Summarization of weather forecast
    */
    'summary'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date"
        },
        {
            "name": "temperatureC",
            "baseName": "temperatureC",
            "type": "number"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WeatherForecastDto.attributeTypeMap;
    }
}

