"use strict";
/**
 * API
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeatherForecastDto = void 0;
class WeatherForecastDto {
    static getAttributeTypeMap() {
        return WeatherForecastDto.attributeTypeMap;
    }
}
exports.WeatherForecastDto = WeatherForecastDto;
WeatherForecastDto.discriminator = undefined;
WeatherForecastDto.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "number"
    },
    {
        "name": "date",
        "baseName": "date",
        "type": "Date"
    },
    {
        "name": "temperatureC",
        "baseName": "temperatureC",
        "type": "number"
    },
    {
        "name": "summary",
        "baseName": "summary",
        "type": "string"
    }
];
//# sourceMappingURL=weatherForecastDto.js.map