/*
 * API
 *
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Weather.Api.Client.Sdk.DotNet.Api;
using Weather.Api.Client.Sdk.DotNet.Model;
using Weather.Api.Client.Sdk.DotNet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Weather.Api.Client.Sdk.DotNet.Test.Model
{
    /// <summary>
    ///  Class for testing HttpValidationProblemDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HttpValidationProblemDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HttpValidationProblemDetails
        //private HttpValidationProblemDetails instance;

        public HttpValidationProblemDetailsTests()
        {
            // TODO uncomment below to create an instance of HttpValidationProblemDetails
            //instance = new HttpValidationProblemDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HttpValidationProblemDetails
        /// </summary>
        [Fact]
        public void HttpValidationProblemDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" HttpValidationProblemDetails
            //Assert.IsType<HttpValidationProblemDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
        /// <summary>
        /// Test the property 'Instance'
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO unit test for the property 'Instance'
        }

    }

}
