/*
 * API
 *
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Weather.Api.Client.Sdk.DotNet.Api;
using Weather.Api.Client.Sdk.DotNet.Model;
using Weather.Api.Client.Sdk.DotNet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Weather.Api.Client.Sdk.DotNet.Test.Model
{
    /// <summary>
    ///  Class for testing LoginCredentials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoginCredentialsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoginCredentials
        //private LoginCredentials instance;

        public LoginCredentialsTests()
        {
            // TODO uncomment below to create an instance of LoginCredentials
            //instance = new LoginCredentials();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoginCredentials
        /// </summary>
        [Fact]
        public void LoginCredentialsInstanceTest()
        {
            // TODO uncomment below to test "IsType" LoginCredentials
            //Assert.IsType<LoginCredentials>(instance);
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
