/*
 * API
 *
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Weather.Api.Client.Sdk.DotNet.Api;
using Weather.Api.Client.Sdk.DotNet.Model;
using Weather.Api.Client.Sdk.DotNet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Weather.Api.Client.Sdk.DotNet.Test.Model
{
    /// <summary>
    ///  Class for testing Token
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Token
        //private Token instance;

        public TokenTests()
        {
            // TODO uncomment below to create an instance of Token
            //instance = new Token();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Token
        /// </summary>
        [Fact]
        public void TokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" Token
            //Assert.IsType<Token>(instance);
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Fact]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }

    }

}
