/*
 * API
 *
 * An Api to perform weather forecasts
 *
 * The version of the OpenAPI document: 1
 * Contact: jon.doe@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Weather.Api.Client.Sdk.DotNet.Api;
using Weather.Api.Client.Sdk.DotNet.Model;
using Weather.Api.Client.Sdk.DotNet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Weather.Api.Client.Sdk.DotNet.Test.Model
{
    /// <summary>
    ///  Class for testing WeatherForecastDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WeatherForecastDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WeatherForecastDto
        //private WeatherForecastDto instance;

        public WeatherForecastDtoTests()
        {
            // TODO uncomment below to create an instance of WeatherForecastDto
            //instance = new WeatherForecastDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WeatherForecastDto
        /// </summary>
        [Fact]
        public void WeatherForecastDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" WeatherForecastDto
            //Assert.IsType<WeatherForecastDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'TemperatureC'
        /// </summary>
        [Fact]
        public void TemperatureCTest()
        {
            // TODO unit test for the property 'TemperatureC'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

    }

}
